# Generated by Django 4.2.13 on 2025-08-11 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentintent',
            name='amount',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
