# Generated by Django 4.2.13 on 2025-08-11 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_paymentintent_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentintent',
            name='amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='paymentintent',
            name='gateway',
            field=models.CharField(choices=[('sadad', 'سداد (بانک ملّی)'), ('fake', 'درگاه آزمایشی')], default='fake', max_length=20),
        ),
    ]
