# Generated by Django 5.2.1 on 2025-09-17 14:28

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0025_tkdboard_ranking_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportCenter',
            fields=[
            ],
            options={
                'verbose_name': 'مرکز گزارش\u200cگیری',
                'verbose_name_plural': 'مرکز گزارش\u200cگیری',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.userprofile',),
        ),
    ]
