# Generated by Django 4.2.13 on 2025-08-07 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='عنوان رده سنی')),
                ('from_date', models.DateField(verbose_name='از تاریخ تولد')),
                ('to_date', models.DateField(verbose_name='تا تاریخ تولد')),
            ],
            options={
                'verbose_name': 'رده سنی',
                'verbose_name_plural': 'رده\u200cهای سنی',
            },
        ),
        migrations.CreateModel(
            name='Belt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام کمربند')),
            ],
            options={
                'verbose_name': 'کمربند',
                'verbose_name_plural': 'کمربندها',
            },
        ),
        migrations.CreateModel(
            name='BeltGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100, verbose_name='نام گروه کمربند')),
                ('belts', models.ManyToManyField(to='competitions.belt', verbose_name='کمربندها')),
            ],
            options={
                'verbose_name': 'گروه کمربند',
                'verbose_name_plural': 'گروه\u200cهای کمربند',
            },
        ),
        migrations.CreateModel(
            name='KyorugiCompetition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان مسابقه')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='kyorugi_posters/', verbose_name='پوستر مسابقه')),
                ('belt_level', models.CharField(choices=[('yellow_blue', 'زرد تا آبی'), ('red_black', 'قرمز و مشکی'), ('all', 'همه رده\u200cها')], max_length=20, verbose_name='رده کمربندی')),
                ('gender', models.CharField(choices=[('male', 'مرد'), ('female', 'زن'), ('both', 'هر دو')], max_length=10, verbose_name='جنسیت')),
                ('city', models.CharField(max_length=100, verbose_name='شهر محل برگزاری')),
                ('address', models.TextField(verbose_name='آدرس محل برگزاری')),
                ('registration_start', models.DateField(verbose_name='شروع ثبت\u200cنام')),
                ('registration_end', models.DateField(verbose_name='پایان ثبت\u200cنام')),
                ('weigh_date', models.DateField(verbose_name='تاریخ وزن\u200cکشی')),
                ('draw_date', models.DateField(verbose_name='تاریخ قرعه\u200cکشی')),
                ('competition_date', models.DateField(verbose_name='تاریخ برگزاری')),
                ('mat_count', models.PositiveIntegerField(default=1, verbose_name='تعداد زمین')),
                ('registration_open', models.BooleanField(default=False, verbose_name='فعال بودن ثبت\u200cنام')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('age_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='competitions.agecategory', verbose_name='رده سنی')),
                ('belt_groups', models.ManyToManyField(blank=True, to='competitions.beltgroup', verbose_name='گروه\u200cهای کمربندی')),
            ],
            options={
                'verbose_name': 'مسابقه کیوروگی',
                'verbose_name_plural': 'مسابقات کیوروگی',
            },
        ),
        migrations.CreateModel(
            name='WeightCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام وزن')),
                ('gender', models.CharField(choices=[('male', 'مرد'), ('female', 'زن')], max_length=6, verbose_name='جنسیت')),
                ('min_weight', models.FloatField(verbose_name='حداقل وزن (kg)')),
                ('max_weight', models.FloatField(verbose_name='حداکثر وزن (kg)')),
                ('tolerance', models.FloatField(default=0.2, verbose_name='میزان ارفاق وزنی (kg)')),
            ],
            options={
                'verbose_name': 'رده وزنی',
                'verbose_name_plural': 'رده\u200cهای وزنی',
            },
        ),
        migrations.CreateModel(
            name='MatAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mat_number', models.PositiveIntegerField(verbose_name='شماره زمین')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mat_assignments', to='competitions.kyorugicompetition', verbose_name='مسابقه')),
                ('weights', models.ManyToManyField(to='competitions.weightcategory', verbose_name='اوزان تخصیص\u200cیافته')),
            ],
            options={
                'verbose_name': 'تخصیص زمین',
                'verbose_name_plural': 'تخصیص اوزان به زمین\u200cها',
            },
        ),
    ]
