# Generated by Django 4.2.13 on 2025-08-07 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0002_alter_kyorugicompetition_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='kyorugicompetition',
            name='entry_fee',
            field=models.PositiveIntegerField(default=0, verbose_name='مبلغ ورودی (تومان)'),
        ),
    ]
