# Generated by Django 4.2.13 on 2025-08-07 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0003_kyorugicompetition_entry_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kyorugicompetition',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='kyorugi_posters/', verbose_name='پوستر شاخص'),
        ),
        migrations.CreateModel(
            name='CompetitionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='kyorugi_images/', verbose_name='تصویر پیوست')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='competitions.kyorugicompetition', verbose_name='مسابقه')),
            ],
            options={
                'verbose_name': 'تصویر مسابقه',
                'verbose_name_plural': 'تصاویر مسابقه',
            },
        ),
        migrations.CreateModel(
            name='CompetitionFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='kyorugi_files/', verbose_name='فایل PDF')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='competitions.kyorugicompetition', verbose_name='مسابقه')),
            ],
            options={
                'verbose_name': 'فایل مسابقه',
                'verbose_name_plural': 'فایل\u200cهای مسابقه',
            },
        ),
    ]
