# Generated by Django 4.2.13 on 2025-08-08 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_coachclubrequest'),
        ('competitions', '0004_alter_kyorugicompetition_poster_competitionimage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kyorugicompetition',
            name='gender',
            field=models.CharField(choices=[('male', 'آقایان'), ('female', 'بانوان')], max_length=10, verbose_name='جنسیت'),
        ),
        migrations.CreateModel(
            name='CoachApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4, verbose_name='کد تأیید مربی')),
                ('terms_accepted', models.BooleanField(default=False, verbose_name='تعهدنامه پذیرفته شد')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('approved_at', models.DateTimeField(auto_now_add=True)),
                ('coach', models.ForeignKey(limit_choices_to={'is_coach': True}, on_delete=django.db.models.deletion.CASCADE, related_name='competition_approvals', to='accounts.userprofile', verbose_name='مربی')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coach_approvals', to='competitions.kyorugicompetition', verbose_name='مسابقه')),
            ],
            options={
                'verbose_name': 'تأیید مربی برای مسابقه',
                'verbose_name_plural': 'تأییدهای مربیان',
                'unique_together': {('competition', 'coach')},
            },
        ),
    ]
