# Generated by Django 4.2.13 on 2025-08-08 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0005_alter_kyorugicompetition_gender_coachapproval'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='coachapproval',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='coachapproval',
            name='code',
            field=models.CharField(blank=True, db_index=True, max_length=4, null=True, verbose_name='کد تأیید مربی'),
        ),
        migrations.AddIndex(
            model_name='coachapproval',
            index=models.Index(fields=['competition', 'is_active', 'terms_accepted'], name='competition_competi_30ddd5_idx'),
        ),
        migrations.AddConstraint(
            model_name='coachapproval',
            constraint=models.UniqueConstraint(fields=('competition', 'coach'), name='uniq_competition_coach'),
        ),
        migrations.AddConstraint(
            model_name='coachapproval',
            constraint=models.UniqueConstraint(fields=('competition', 'code'), name='uniq_competition_code'),
        ),
    ]
