# Generated by Django 4.2.13 on 2025-08-08 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0006_alter_coachapproval_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coachapproval',
            name='approved_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ تأیید'),
        ),
    ]
