# Generated by Django 4.2.13 on 2025-08-09 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0007_alter_coachapproval_approved_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='kyorugicompetition',
            name='public_id',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=16, null=True, unique=True, verbose_name='شناسه عمومی'),
        ),
    ]
