# Generated by Django 4.2.13 on 2025-08-10 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0008_kyorugicompetition_public_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='kyorugicompetition',
            name='terms_text',
            field=models.TextField(blank=True, default='', verbose_name='متن تعهدنامه مربی'),
        ),
    ]
