# Generated by Django 4.2.13 on 2025-08-10 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0009_kyorugicompetition_terms_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermsTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان تعهدنامه')),
                ('content', models.TextField(verbose_name='متن تعهدنامه')),
            ],
            options={
                'verbose_name': 'قالب تعهدنامه',
                'verbose_name_plural': 'قالب\u200cهای تعهدنامه',
            },
        ),
    ]
