# Generated by Django 4.2.13 on 2025-08-10 13:13

import competitions.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0010_termstemplate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kyorugicompetition',
            name='terms_text',
        ),
        migrations.AddField(
            model_name='kyorugicompetition',
            name='terms_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='competitions', to='competitions.termstemplate', verbose_name='قالب تعهدنامه'),
        ),
        migrations.AlterField(
            model_name='kyorugicompetition',
            name='public_id',
            field=models.CharField(db_index=True, default=competitions.models._gen_public_id, editable=False, max_length=16, unique=True, verbose_name='شناسه عمومی'),
        ),
        migrations.AddIndex(
            model_name='kyorugicompetition',
            index=models.Index(fields=['public_id'], name='competition_public__f756e4_idx'),
        ),
        migrations.AddIndex(
            model_name='kyorugicompetition',
            index=models.Index(fields=['competition_date'], name='competition_competi_cafbd9_idx'),
        ),
        migrations.AddConstraint(
            model_name='kyorugicompetition',
            constraint=models.CheckConstraint(check=models.Q(('registration_start__lte', models.F('registration_end'))), name='reg_start_lte_reg_end'),
        ),
        migrations.AddConstraint(
            model_name='kyorugicompetition',
            constraint=models.CheckConstraint(check=models.Q(('weigh_date__lte', models.F('draw_date'))), name='weigh_lte_draw'),
        ),
        migrations.AddConstraint(
            model_name='kyorugicompetition',
            constraint=models.CheckConstraint(check=models.Q(('draw_date__lte', models.F('competition_date'))), name='draw_lte_comp'),
        ),
    ]
