# Generated by Django 4.2.13 on 2025-08-11 22:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_coachclubrequest'),
        ('payments', '0002_alter_paymentintent_amount'),
        ('competitions', '0011_remove_kyorugicompetition_terms_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitionDivision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان Division')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('notes', models.TextField(blank=True, default='', verbose_name='توضیحات')),
                ('belts', models.ManyToManyField(blank=True, to='competitions.belt', verbose_name='کمربندهای مجاز')),
            ],
            options={
                'verbose_name': 'زیرگروه کمربندی',
                'verbose_name_plural': 'زیرگروه\u200cهای کمربندی',
                'ordering': ['competition', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DivisionWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='division_weights', to='competitions.competitiondivision', verbose_name='Division')),
                ('weight_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='in_divisions', to='competitions.weightcategory', verbose_name='رده وزنی')),
            ],
            options={
                'verbose_name': 'وزنِ Division',
                'verbose_name_plural': 'وزن\u200cهای Division',
                'ordering': ['division', 'order', 'id'],
                'unique_together': {('division', 'weight_category')},
            },
        ),
        migrations.AlterField(
            model_name='coachapproval',
            name='code',
            field=models.CharField(blank=True, db_index=True, max_length=8, null=True, verbose_name='کد تأیید مربی'),
        ),
        migrations.AlterField(
            model_name='kyorugicompetition',
            name='entry_fee',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='مبلغ ورودی (تومان)'),
        ),
        migrations.AddField(
            model_name='competitiondivision',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='divisions', to='competitions.kyorugicompetition', verbose_name='مسابقه'),
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('declared_weight', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='وزن اعلامی (kg)')),
                ('insurance_number', models.CharField(max_length=20, verbose_name='شماره بیمه')),
                ('insurance_issue_date', models.DateField(verbose_name='تاریخ صدور بیمه\u200cنامه')),
                ('status', models.CharField(choices=[('pending_payment', 'در انتظار پرداخت'), ('paid', 'پرداخت\u200cشده'), ('canceled', 'لغو/باطل')], default='pending_payment', max_length=20, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('coach', models.ForeignKey(blank=True, limit_choices_to={'is_coach': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coach_enrollments', to='accounts.userprofile', verbose_name='مربی')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='competitions.kyorugicompetition', verbose_name='مسابقه')),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='competitions.competitiondivision', verbose_name='زیرگروه کمربندی')),
                ('division_weight', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='competitions.divisionweight', verbose_name='وزن انتخابی')),
                ('payment_intent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollments', to='payments.paymentintent', verbose_name='تراکنش')),
                ('player', models.ForeignKey(limit_choices_to={'role__in': ['player', 'both']}, on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='accounts.userprofile', verbose_name='بازیکن')),
            ],
            options={
                'verbose_name': 'ثبت\u200cنام',
                'verbose_name_plural': 'ثبت\u200cنام\u200cها',
                'indexes': [models.Index(fields=['competition', 'status'], name='competition_competi_e9adb2_idx'), models.Index(fields=['division'], name='competition_divisio_f7630c_idx'), models.Index(fields=['division_weight'], name='competition_divisio_42104b_idx')],
                'unique_together': {('competition', 'player')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='competitiondivision',
            unique_together={('competition', 'title')},
        ),
    ]
