# Generated by Django 4.2.13 on 2025-08-11 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_coachclubrequest'),
        ('competitions', '0012_competitiondivision_divisionweight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='bank_ref_code',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='کد پیگیری بانک'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='club',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_club': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='club_enrollments', to='accounts.userprofile', verbose_name='باشگاه'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='club_name',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='نام باشگاه (هنگام ثبت\u200cنام)'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='coach_approval_code',
            field=models.CharField(blank=True, default='', max_length=8, verbose_name='کد تأیید مربی (در هنگام ثبت)'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='coach_name',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='نام مربی (هنگام ثبت\u200cنام)'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='پرداخت موفق؟'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='paid_amount',
            field=models.PositiveIntegerField(default=0, verbose_name='مبلغ واریزی (تومان)'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پرداخت'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['coach'], name='competition_coach_i_e3c33b_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['club'], name='competition_club_id_a81a7c_idx'),
        ),
    ]
