# Generated by Django 4.2.13 on 2025-08-12 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0013_enrollment_bank_ref_code_enrollment_club_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='competitiondivision',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='competitiondivision',
            name='belts',
        ),
        migrations.RemoveField(
            model_name='competitiondivision',
            name='competition',
        ),
        migrations.AlterUniqueTogether(
            name='divisionweight',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='divisionweight',
            name='division',
        ),
        migrations.RemoveField(
            model_name='divisionweight',
            name='weight_category',
        ),
        migrations.RemoveIndex(
            model_name='enrollment',
            name='competition_divisio_f7630c_idx',
        ),
        migrations.RemoveIndex(
            model_name='enrollment',
            name='competition_divisio_42104b_idx',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='division',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='division_weight',
        ),
        migrations.AddField(
            model_name='enrollment',
            name='belt_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='competitions.beltgroup', verbose_name='گروه کمربندی'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='weight_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='competitions.weightcategory', verbose_name='رده وزنی'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['belt_group'], name='competition_belt_gr_2296cd_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['weight_category'], name='competition_weight__61fdc0_idx'),
        ),
        migrations.DeleteModel(
            name='CompetitionDivision',
        ),
        migrations.DeleteModel(
            name='DivisionWeight',
        ),
    ]
