# Generated by Django 4.2.13 on 2025-08-12 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0014_alter_competitiondivision_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='coachapproval',
            name='uniq_competition_code',
        ),
        migrations.AddConstraint(
            model_name='coachapproval',
            constraint=models.UniqueConstraint(condition=models.Q(('code__isnull', False)), fields=('competition', 'code'), name='uniq_competition_code'),
        ),
    ]
