# Generated by Django 4.2.13 on 2025-08-12 15:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_coachclubrequest'),
        ('competitions', '0015_remove_coachapproval_uniq_competition_code_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enrollment',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='enrollment',
            name='competition_belt_gr_2296cd_idx',
        ),
        migrations.RemoveIndex(
            model_name='enrollment',
            name='competition_weight__61fdc0_idx',
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='board',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='board_enrollments', to='accounts.tkdboard'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='board_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='bank_ref_code',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='belt_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollments', to='competitions.beltgroup'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='club_enrollments', to='accounts.tkdclub'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='club_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='coach',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_coach': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coach_enrollments', to='accounts.userprofile'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='coach_approval_code',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='coach_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='competitions.kyorugicompetition'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='declared_weight',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='insurance_issue_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='insurance_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='paid_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='accounts.userprofile'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('pending_payment', 'در انتظار پرداخت'), ('paid', 'پرداخت\u200cشده'), ('confirmed', 'تأیید نهایی'), ('accepted', 'پذیرفته\u200cشده'), ('completed', 'تکمیل\u200cشده'), ('canceled', 'لغو شده')], default='pending_payment', max_length=20),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='weight_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='competitions.weightcategory'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['board'], name='competition_board_i_f2dec0_idx'),
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='payment_intent',
        ),
    ]
