# Generated by Django 4.2.13 on 2025-08-13 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_coachclubrequest'),
        ('competitions', '0016_alter_enrollment_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Draw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=10, verbose_name='جنسیت')),
                ('size', models.PositiveIntegerField(help_text='مثل 8، 16، 32', verbose_name='اندازه جدول (توان ۲)')),
                ('club_threshold', models.PositiveIntegerField(default=8, verbose_name='آستانه هم\u200cباشگاهی')),
                ('rng_seed', models.CharField(blank=True, default='', max_length=32, verbose_name='Seed تصادفی')),
                ('is_locked', models.BooleanField(default=False, verbose_name='قفل شده؟')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد')),
                ('age_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='competitions.agecategory', verbose_name='رده سنی')),
                ('belt_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='competitions.beltgroup', verbose_name='گروه کمربندی')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draws', to='competitions.kyorugicompetition', verbose_name='مسابقه')),
                ('weight_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='competitions.weightcategory', verbose_name='رده وزنی')),
            ],
            options={
                'verbose_name': 'قرعه',
                'verbose_name_plural': 'قرعه\u200cها',
            },
        ),
        migrations.CreateModel(
            name='KyorugiCompetitionParticipantsReport',
            fields=[
            ],
            options={
                'verbose_name': 'لیست شرکت\u200cکنندگان مسابقات',
                'verbose_name_plural': 'لیست شرکت\u200cکنندگان مسابقات',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('competitions.kyorugicompetition',),
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_no', models.PositiveIntegerField(help_text='1 = دور اول', verbose_name='دور')),
                ('slot_a', models.PositiveIntegerField(verbose_name='اسلات A')),
                ('slot_b', models.PositiveIntegerField(verbose_name='اسلات B')),
                ('is_bye', models.BooleanField(default=False, verbose_name='BYE؟')),
                ('mat_no', models.PositiveIntegerField(blank=True, null=True, verbose_name='زمین')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان\u200cبندی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد')),
                ('draw', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='competitions.draw', verbose_name='قرعه')),
                ('player_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='as_player_a', to='accounts.userprofile', verbose_name='بازیکن A')),
                ('player_b', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='as_player_b', to='accounts.userprofile', verbose_name='بازیکن B')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='as_winner', to='accounts.userprofile', verbose_name='برنده')),
            ],
            options={
                'verbose_name': 'مبارزه',
                'verbose_name_plural': 'مبارزات',
                'indexes': [models.Index(fields=['draw', 'round_no'], name='competition_draw_id_bc410e_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='draw',
            index=models.Index(fields=['competition', 'gender', 'age_category', 'belt_group', 'weight_category'], name='competition_competi_9305f8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='draw',
            unique_together={('competition', 'gender', 'age_category', 'belt_group', 'weight_category')},
        ),
    ]
