# Generated by Django 4.2.13 on 2025-08-13 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0017_draw_kyorugicompetitionparticipantsreport_match_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrawStart',
            fields=[
            ],
            options={
                'verbose_name': 'شروع قرعه\u200cکشی',
                'verbose_name_plural': 'شروع قرعه\u200cکشی',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('competitions.draw',),
        ),
    ]
