# Generated by Django 4.2.13 on 2025-08-13 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_coachclubrequest'),
        ('competitions', '0018_drawstart'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirstRoundPairHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=10)),
                ('last_met_at', models.DateTimeField(auto_now=True)),
                ('age_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='competitions.agecategory')),
                ('belt_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='competitions.beltgroup')),
                ('last_competition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='competitions.kyorugicompetition')),
                ('player_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.userprofile')),
                ('player_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.userprofile')),
                ('weight_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='competitions.weightcategory')),
            ],
            options={
                'unique_together': {('player_a', 'player_b', 'gender', 'age_category', 'belt_group', 'weight_category')},
            },
        ),
    ]
