# Generated by Django 4.2.13 on 2025-08-28 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0019_firstroundpairhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitionMatchNumbering',
            fields=[
            ],
            options={
                'verbose_name': 'شماره\u200cگذاری و چاپ بازی\u200cها',
                'verbose_name_plural': 'شماره\u200cگذاری و چاپ بازی\u200cها',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('competitions.kyorugicompetition',),
        ),
        migrations.AddField(
            model_name='match',
            name='order_on_mat',
            field=models.PositiveIntegerField(blank=True, db_index=True, help_text='شماره\u200cی اجرای این مسابقه روی زمین (از ۱ شروع می\u200cشود)', null=True, verbose_name='شمارهٔ بازی در زمین'),
        ),
        migrations.AlterField(
            model_name='match',
            name='mat_no',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='زمین'),
        ),
        migrations.AlterUniqueTogether(
            name='match',
            unique_together={('mat_no', 'order_on_mat'), ('draw', 'round_no', 'slot_a', 'slot_b')},
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['mat_no', 'order_on_mat'], name='competition_mat_no_2cc0c0_idx'),
        ),
    ]
