# Generated by Django 4.2.13 on 2025-08-28 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0020_competitionmatchnumbering_match_order_on_mat_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='match',
            name='competition_mat_no_2cc0c0_idx',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='mat_no',
            new_name='mat_number',
        ),
        migrations.AlterUniqueTogether(
            name='match',
            unique_together={('draw', 'round_no', 'slot_a', 'slot_b')},
        ),
        migrations.AlterField(
            model_name='match',
            name='order_on_mat',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='شمارهٔ بازی در زمین'),
        ),
        migrations.AlterUniqueTogether(
            name='match',
            unique_together={('mat_number', 'order_on_mat'), ('draw', 'round_no', 'slot_a', 'slot_b')},
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['mat_number', 'order_on_mat'], name='competition_mat_num_8389fc_idx'),
        ),
    ]
