# Generated by Django 4.2.13 on 2025-08-28 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0021_remove_match_competition_mat_no_2cc0c0_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='match',
            name='competition_mat_num_8389fc_idx',
        ),
        migrations.AlterUniqueTogether(
            name='match',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='match',
            name='mat_no',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='زمین'),
        ),
        migrations.AddField(
            model_name='match',
            name='match_number',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='شماره بازی'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['mat_no', 'match_number'], name='competition_mat_no_fb64cc_idx'),
        ),
        migrations.RemoveField(
            model_name='match',
            name='mat_number',
        ),
        migrations.RemoveField(
            model_name='match',
            name='order_on_mat',
        ),
    ]
