# Generated by Django 4.2.13 on 2025-09-06 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0022_remove_match_competition_mat_num_8389fc_idx_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompetitionMatchNumbering',
        ),
        migrations.CreateModel(
            name='MatchNumberingProxy',
            fields=[
            ],
            options={
                'verbose_name': 'شماره\u200cگذاری بازی\u200cها',
                'verbose_name_plural': 'شماره\u200cگذاری بازی\u200cها',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('competitions.kyorugicompetition',),
        ),
    ]
