# Generated by Django 4.2.13 on 2025-09-08 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_tkdboard_ranking_total'),
        ('competitions', '0023_delete_competitionmatchnumbering_matchnumberingproxy'),
    ]

    operations = [
        migrations.CreateModel(
            name='RankingAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(blank=True, max_length=255)),
                ('coach_name', models.CharField(blank=True, max_length=255)),
                ('club_name', models.CharField(blank=True, max_length=255)),
                ('board_name', models.CharField(blank=True, max_length=255)),
                ('points_player', models.FloatField(default=0.0)),
                ('points_coach', models.FloatField(default=0.0)),
                ('points_club', models.FloatField(default=0.0)),
                ('points_board', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('board', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='awards_as_board', to='accounts.tkdboard')),
                ('club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='awards_as_club', to='accounts.tkdclub')),
                ('coach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='awards_as_coach', to='accounts.userprofile')),
                ('enrollment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ranking_award', to='competitions.enrollment')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='awards_as_player', to='accounts.userprofile')),
            ],
        ),
    ]
