# Generated by Django 4.2.13 on 2025-09-09 19:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('competitions', '0024_rankingaward'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='medal',
            field=models.CharField(blank=True, choices=[('', '—'), ('gold', 'طلا'), ('silver', 'نقره'), ('bronze', 'برنز')], default='', max_length=10),
        ),
        migrations.CreateModel(
            name='KyorugiResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bronze1_enrollment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='competitions.enrollment')),
                ('bronze2_enrollment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='competitions.enrollment')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='competitions.kyorugicompetition')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('gold_enrollment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='competitions.enrollment')),
                ('silver_enrollment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='competitions.enrollment')),
                ('weight_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='competitions.weightcategory')),
            ],
            options={
                'verbose_name': 'نتیجه وزن',
                'verbose_name_plural': 'نتایج اوزان',
                'unique_together': {('competition', 'weight_category')},
            },
        ),
        migrations.CreateModel(
            name='RankingTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_type', models.CharField(choices=[('player', 'بازیکن'), ('coach', 'مربی'), ('club', 'باشگاه'), ('board', 'هیئت')], max_length=16)),
                ('subject_id', models.IntegerField()),
                ('medal', models.CharField(blank=True, default='', max_length=10)),
                ('points', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranking_transactions', to='competitions.kyorugicompetition')),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='competitions.kyorugiresult')),
            ],
            options={
                'indexes': [models.Index(fields=['competition', 'subject_type', 'subject_id'], name='competition_competi_a5485b_idx'), models.Index(fields=['result'], name='competition_result__adf0f9_idx')],
            },
        ),
    ]
