# Generated by Django 4.2.13 on 2025-09-10 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0025_enrollment_medal_kyorugiresult_rankingtransaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnounceResultsProxy',
            fields=[
            ],
            options={
                'verbose_name': 'اعلام نتایج',
                'verbose_name_plural': 'اعلام نتایج',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('competitions.kyorugicompetition',),
        ),
    ]
