# Generated by Django 4.2.13 on 2025-09-13 19:03

import competitions.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('competitions', '0026_announceresultsproxy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seminar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('poster', models.ImageField(blank=True, null=True, upload_to='seminars/posters/')),
                ('description', models.TextField(blank=True)),
                ('registration_start', models.DateField()),
                ('registration_end', models.DateField()),
                ('event_date', models.DateField()),
                ('location', models.CharField(blank=True, max_length=255)),
                ('fee', models.PositiveIntegerField(default=0)),
                ('allowed_roles', models.JSONField(default=list, help_text="مثلاً ['player','coach']")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('public_id', models.CharField(db_index=True, default=competitions.models._gen_seminar_public_id, editable=False, max_length=16, unique=True)),
            ],
            options={
                'verbose_name': 'سمینار',
                'verbose_name_plural': 'سمینارها',
            },
        ),
        migrations.CreateModel(
            name='SeminarRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roles', models.JSONField(default=list, help_text="مثال: ['coach']")),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('note', models.TextField(blank=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('paid_amount', models.PositiveIntegerField(default=0)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seminar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='competitions.seminar')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seminar_registrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ثبت\u200cنام سمینار',
                'verbose_name_plural': 'ثبت\u200cنام\u200cهای سمینار',
            },
        ),
        migrations.AddIndex(
            model_name='seminar',
            index=models.Index(fields=['public_id'], name='competition_public__3683fa_idx'),
        ),
        migrations.AddIndex(
            model_name='seminar',
            index=models.Index(fields=['event_date'], name='competition_event_d_ff54ff_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='seminarregistration',
            unique_together={('seminar', 'user')},
        ),
    ]
