# Generated by Django 4.2.13 on 2025-09-14 13:11

import competitions.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('competitions', '0027_seminar_seminarregistration_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MatchNumberingProxy',
        ),
        migrations.AlterModelOptions(
            name='seminar',
            options={'ordering': ['-event_date', '-created_at'], 'verbose_name': 'سمینار', 'verbose_name_plural': 'سمینارها'},
        ),
        migrations.AlterField(
            model_name='seminar',
            name='allowed_roles',
            field=models.JSONField(blank=True, default=list, help_text="مثلاً ['player','coach'] — خالی = همه نقش\u200cها", verbose_name='نقش\u200cهای مجاز'),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده در'),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='description',
            field=models.TextField(blank=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='event_date',
            field=models.DateField(verbose_name='تاریخ برگزاری'),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='fee',
            field=models.PositiveIntegerField(default=0, verbose_name='هزینه (تومان)'),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='location',
            field=models.CharField(blank=True, max_length=255, verbose_name='مکان برگزاری'),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='seminars/posters/', verbose_name='پوستر'),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='public_id',
            field=models.CharField(db_index=True, default=competitions.models._seminar_default_public_id, editable=False, max_length=16, unique=True, verbose_name='شناسه عمومی'),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='registration_end',
            field=models.DateField(verbose_name='پایان ثبت\u200cنام'),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='registration_start',
            field=models.DateField(verbose_name='شروع ثبت\u200cنام'),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='title',
            field=models.CharField(max_length=255, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='seminarregistration',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده در'),
        ),
        migrations.AlterField(
            model_name='seminarregistration',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='پرداخت شده'),
        ),
        migrations.AlterField(
            model_name='seminarregistration',
            name='note',
            field=models.TextField(blank=True, verbose_name='یادداشت'),
        ),
        migrations.AlterField(
            model_name='seminarregistration',
            name='paid_amount',
            field=models.PositiveIntegerField(default=0, verbose_name='مبلغ پرداختی (تومان)'),
        ),
        migrations.AlterField(
            model_name='seminarregistration',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان پرداخت'),
        ),
        migrations.AlterField(
            model_name='seminarregistration',
            name='phone',
            field=models.CharField(blank=True, max_length=40, verbose_name='تلفن تماس'),
        ),
        migrations.AlterField(
            model_name='seminarregistration',
            name='roles',
            field=models.JSONField(blank=True, default=list, help_text="مثال: ['coach']", verbose_name='نقش/نقش\u200cها'),
        ),
        migrations.AlterField(
            model_name='seminarregistration',
            name='seminar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='competitions.seminar', verbose_name='سمینار'),
        ),
        migrations.AlterField(
            model_name='seminarregistration',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seminar_registrations', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
    ]
