# Generated by Django 4.2.13 on 2025-09-14 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0028_delete_matchnumberingproxy_alter_seminar_options_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='seminar',
            constraint=models.CheckConstraint(check=models.Q(('registration_start__lte', models.F('registration_end'))), name='seminar_reg_start_lte_reg_end'),
        ),
        migrations.AddConstraint(
            model_name='seminar',
            constraint=models.CheckConstraint(check=models.Q(('registration_end__lte', models.F('event_date'))), name='seminar_reg_end_lte_event_date'),
        ),
    ]
