# Generated by Django 4.2.13 on 2025-09-14 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0029_seminar_seminar_reg_start_lte_reg_end_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeminarAttendee',
            fields=[
            ],
            options={
                'verbose_name': 'شرکت\u200cکنندهٔ سمینار',
                'verbose_name_plural': 'لیست شرکت\u200cکنندگان سمینارها',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('competitions.seminarregistration',),
        ),
        migrations.CreateModel(
            name='SeminarParticipants',
            fields=[
            ],
            options={
                'verbose_name': 'لیست شرکت\u200cکنندگان سمینارها',
                'verbose_name_plural': 'لیست شرکت\u200cکنندگان سمینارها',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('competitions.seminarregistration',),
        ),
    ]
