# Generated by Django 5.2.1 on 2025-09-21 16:25

import competitions.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0030_seminarattendee_seminarparticipants'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchNumberingEntry',
            fields=[
            ],
            options={
                'verbose_name': 'شماره\u200cگذاری بازی\u200cها',
                'verbose_name_plural': 'شماره\u200cگذاری بازی\u200cها',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('competitions.kyorugicompetition',),
        ),
        migrations.AlterModelOptions(
            name='seminarattendee',
            options={'verbose_name': 'لیست شرکت\u200cکنندگان سمینارها', 'verbose_name_plural': 'لیست شرکت\u200cکنندگان سمینارها'},
        ),
        migrations.CreateModel(
            name='PoomsaeCompetition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان مسابقه')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='poomsae_posters/', verbose_name='پوستر شاخص')),
                ('entry_fee', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='مبلغ ورودی (تومان)')),
                ('belt_level', models.CharField(choices=[('yellow_blue', 'زرد تا آبی'), ('red_black', 'قرمز و مشکی')], max_length=20, verbose_name='رده کمربندی')),
                ('gender', models.CharField(choices=[('male', 'آقایان'), ('female', 'بانوان')], max_length=10, verbose_name='جنسیت')),
                ('city', models.CharField(max_length=100, verbose_name='شهر محل برگزاری')),
                ('address', models.TextField(blank=True, default='', verbose_name='آدرس محل برگزاری')),
                ('registration_start', models.DateField(verbose_name='شروع ثبت\u200cنام')),
                ('registration_end', models.DateField(verbose_name='پایان ثبت\u200cنام')),
                ('draw_date', models.DateField(blank=True, null=True, verbose_name='تاریخ قرعه\u200cکشی')),
                ('competition_date', models.DateField(verbose_name='تاریخ برگزاری')),
                ('registration_open', models.BooleanField(default=False, verbose_name='فعال بودن ثبت\u200cنام')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('public_id', models.CharField(db_index=True, default=competitions.models._gen_public_id, editable=False, max_length=16, unique=True, verbose_name='شناسه عمومی')),
                ('age_categories', models.ManyToManyField(blank=True, related_name='poomsae_competitions', to='competitions.agecategory', verbose_name='رده\u200cهای سنی')),
                ('belt_groups', models.ManyToManyField(blank=True, to='competitions.beltgroup', verbose_name='گروه\u200cهای کمربندی')),
            ],
            options={
                'verbose_name': 'مسابقه پومسه',
                'verbose_name_plural': 'مسابقات پومسه',
                'ordering': ('-competition_date', '-id'),
            },
        ),
        migrations.CreateModel(
            name='PoomsaeFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='poomsae_files/', verbose_name='فایل PDF')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='competitions.poomsaecompetition', verbose_name='مسابقه')),
            ],
            options={
                'verbose_name': 'فایل مسابقه پومسه',
                'verbose_name_plural': 'فایل\u200cهای مسابقه پومسه',
            },
        ),
        migrations.CreateModel(
            name='PoomsaeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='poomsae_images/', verbose_name='تصویر پیوست')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='competitions.poomsaecompetition', verbose_name='مسابقه')),
            ],
            options={
                'verbose_name': 'تصویر مسابقه پومسه',
                'verbose_name_plural': 'تصاویر مسابقه پومسه',
            },
        ),
        migrations.AddIndex(
            model_name='poomsaecompetition',
            index=models.Index(fields=['public_id'], name='competition_public__3b1384_idx'),
        ),
        migrations.AddIndex(
            model_name='poomsaecompetition',
            index=models.Index(fields=['competition_date'], name='competition_competi_8f50e0_idx'),
        ),
        migrations.AddConstraint(
            model_name='poomsaecompetition',
            constraint=models.CheckConstraint(condition=models.Q(('registration_start__lte', models.F('registration_end'))), name='poom_reg_start_lte_reg_end'),
        ),
        migrations.AddConstraint(
            model_name='poomsaecompetition',
            constraint=models.CheckConstraint(condition=models.Q(('draw_date__lte', models.F('competition_date')), ('draw_date__isnull', True), _connector='OR'), name='poom_draw_lte_comp_or_null'),
        ),
    ]
