# Generated by Django 5.2.1 on 2025-09-28 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_tkdboard_ranking_total'),
        ('competitions', '0031_matchnumberingentry_alter_seminarattendee_options_and_more'),
    ]

    operations = [
        # ستون terms_template از قبل وجود دارد → فقط State
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='poomsaecompetition',
                    name='terms_template',
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='poomsae_competitions',
                        to='competitions.termstemplate',
                        verbose_name='قالب تعهدنامه',
                    ),
                ),
            ],
            database_operations=[],
        ),

        # جدول PoomsaeDivision از قبل وجود دارد → فقط State
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='PoomsaeDivision',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('gender', models.CharField(choices=[('male', 'آقایان'), ('female', 'بانوان')], max_length=10, verbose_name='جنسیت')),
                        ('poomsae_type', models.CharField(choices=[('standard', 'استاندارد'), ('creative', 'ابداعی')], default='standard', max_length=16, verbose_name='نوع پومسه')),
                        ('age_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='competitions.agecategory', verbose_name='رده سنی')),
                        ('belt_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='competitions.beltgroup', verbose_name='گروه کمربندی')),
                        ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='divisions', to='competitions.poomsaecompetition', verbose_name='مسابقه')),
                    ],
                    options={
                        'verbose_name': 'دیویژن پومسه',
                        'verbose_name_plural': 'دیویژن\u200cهای پومسه',
                    },
                ),
            ],
            database_operations=[],
        ),

        # جدول PoomsaeEntry از قبل وجود دارد → فقط State
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='PoomsaeEntry',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('is_paid', models.BooleanField(default=False)),
                        ('paid_amount', models.PositiveIntegerField(default=0)),
                        ('paid_at', models.DateTimeField(blank=True, null=True)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('insurance_number', models.CharField(blank=True, default='', max_length=20)),
                        ('insurance_issue_date', models.DateField(blank=True, null=True)),
                        ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='competitions.poomsaecompetition', verbose_name='مسابقه')),
                        ('division', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='competitions.poomsaedivision', verbose_name='دیویژن')),
                        ('player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='poomsae_entries', to='accounts.userprofile', verbose_name='بازیکن')),
                    ],
                    options={
                        'verbose_name': 'ثبت\u200cنام پومسه',
                        'verbose_name_plural': 'ثبت\u200cنام\u200cهای پومسه',
                    },
                ),
            ],
            database_operations=[],
        ),

        # جدول PoomsaeCoachApproval هم از قبل وجود دارد → فقط State
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='PoomsaeCoachApproval',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('code', models.CharField(blank=True, db_index=True, max_length=8, null=True, verbose_name='کد تأیید مربی')),
                        ('terms_accepted', models.BooleanField(default=False, verbose_name='تعهدنامه پذیرفته شد')),
                        ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                        ('approved_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ تأیید')),
                        ('coach', models.ForeignKey(limit_choices_to={'is_coach': True}, on_delete=django.db.models.deletion.CASCADE, related_name='poomsae_competition_approvals', to='accounts.userprofile', verbose_name='مربی')),
                        ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coach_approvals', to='competitions.poomsaecompetition', verbose_name='مسابقه پومسه')),
                    ],
                    options={
                        'verbose_name': 'تأیید مربی برای مسابقه پومسه',
                        'verbose_name_plural': 'تأییدهای مربیان (پومسه)',
                        'indexes': [models.Index(fields=['competition', 'is_active', 'terms_accepted'], name='competition_competi_960643_idx')],
                        'constraints': [
                            models.UniqueConstraint(fields=('competition', 'coach'), name='uniq_poom_competition_coach'),
                            models.UniqueConstraint(condition=models.Q(('code__isnull', False)), fields=('competition', 'code'), name='uniq_poom_competition_code'),
                        ],
                    },
                ),
            ],
            database_operations=[],
        ),

        # این‌ها را فعلاً معمولی نگه‌دار تا اگر در DB وجود ندارند ساخته شوند
        migrations.AddIndex(
            model_name='poomsaedivision',
            index=models.Index(fields=['competition', 'gender', 'age_category', 'belt_group', 'poomsae_type'], name='competition_competi_c4be93_idx'),
        ),
        migrations.AddConstraint(
            model_name='poomsaedivision',
            constraint=models.UniqueConstraint(fields=('competition', 'gender', 'age_category', 'belt_group', 'poomsae_type'), name='uniq_poom_division_comp_gender_age_beltgroup_type'),
        ),
        migrations.AddIndex(
            model_name='poomsaeentry',
            index=models.Index(fields=['competition', 'division', 'player'], name='competition_competi_7f0eb1_idx'),
        ),
        migrations.AddConstraint(
            model_name='poomsaeentry',
            constraint=models.UniqueConstraint(fields=('division', 'player'), name='uniq_poom_entry_division_player'),
        ),
    ]
