# Generated by Django 5.2.1 on 2025-09-29 19:16

import competitions.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_tkdboard_ranking_total'),
        ('competitions', '0033_remove_poomsaecompetition_age_categories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='as_winner', to='accounts.userprofile', verbose_name='ברنده'),
        ),
        migrations.CreateModel(
            name='PoomsaeCompetition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.SlugField(default=competitions.models._gen_public_id, editable=False, max_length=16, unique=True, verbose_name='شناسه عمومی')),
                ('name', models.CharField(max_length=255, verbose_name='عنوان مسابقه')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('start_date', models.DateField(verbose_name='تاریخ شروع مسابقه')),
                ('end_date', models.DateField(verbose_name='تاریخ پایان مسابقه')),
                ('registration_start', models.DateTimeField(verbose_name='شروع ثبت\u200cنام')),
                ('registration_end', models.DateTimeField(verbose_name='پایان ثبت\u200cنام')),
                ('entry_fee', models.PositiveIntegerField(default=0, verbose_name='هزینه ورودی (تومان)')),
                ('terms_text', models.TextField(blank=True, verbose_name='متن قوانین و مقررات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'مسابقه پومسه',
                'verbose_name_plural': 'مسابقات پومسه',
                'ordering': ['-start_date', '-created_at'],
                'indexes': [models.Index(fields=['public_id'], name='competition_public__3b1384_idx'), models.Index(fields=['start_date'], name='competition_start_d_b4b3a4_idx'), models.Index(fields=['registration_start', 'registration_end'], name='competition_registr_1718e5_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('start_date__lte', models.F('end_date'))), name='poomsae_start_lte_end'), models.CheckConstraint(condition=models.Q(('registration_start__lte', models.F('registration_end'))), name='poomsae_reg_start_lte_end'), models.CheckConstraint(condition=models.Q(('registration_end__lte', models.F('start_date'))), name='poomsae_reg_end_lte_start_date')],
            },
        ),
        migrations.CreateModel(
            name='PoomsaeDivision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style', models.CharField(choices=[('standard', 'استاندارد'), ('creative', 'ابداعی')], max_length=20, verbose_name='سبک مسابقه')),
                ('age_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competitions.agecategory', verbose_name='گروه سنی')),
                ('belt_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competitions.beltgroup', verbose_name='رده کمربندی')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='divisions', to='competitions.poomsaecompetition', verbose_name='مسابقه')),
            ],
            options={
                'verbose_name': 'رده پومسه',
                'verbose_name_plural': 'رده\u200cهای پومسه',
            },
        ),
        migrations.CreateModel(
            name='PoomsaeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid', models.BooleanField(default=False, verbose_name='پرداخت شده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد')),
                ('coach', models.ForeignKey(blank=True, limit_choices_to={'is_coach': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='poomsae_coach_entries', to='accounts.userprofile', verbose_name='مربی')),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='competitions.poomsaedivision', verbose_name='رده')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poomsae_entries', to='accounts.userprofile', verbose_name='بازیکن')),
            ],
            options={
                'verbose_name': 'ثبت\u200cنام پومسه',
                'verbose_name_plural': 'ثبت\u200cنام\u200cهای پومسه',
            },
        ),
        migrations.CreateModel(
            name='PoomsaeCoachApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, db_index=True, max_length=8, null=True, verbose_name='کد تأیید مربی')),
                ('approved', models.BooleanField(default=False, verbose_name='تأیید شده')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='به\u200cروزرسانی')),
                ('coach', models.ForeignKey(limit_choices_to={'is_coach': True}, on_delete=django.db.models.deletion.CASCADE, related_name='poomsae_coach_approvals', to='accounts.userprofile', verbose_name='مربی')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poomsae_approvals', to='accounts.userprofile', verbose_name='بازیکن')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coach_approvals', to='competitions.poomsaecompetition', verbose_name='مسابقه')),
            ],
            options={
                'verbose_name': 'تأیید مربی پومسه',
                'verbose_name_plural': 'تأییدهای مربی پومسه',
                'indexes': [models.Index(fields=['competition', 'is_active', 'approved'], name='competition_competi_772bb2_idx')],
                'constraints': [models.UniqueConstraint(fields=('competition', 'player'), name='uniq_poomsae_competition_player'), models.UniqueConstraint(condition=models.Q(('code__isnull', False)), fields=('competition', 'code'), name='uniq_poomsae_competition_code')],
            },
        ),
        migrations.AddIndex(
            model_name='poomsaedivision',
            index=models.Index(fields=['competition', 'age_category', 'belt_group', 'style'], name='competition_competi_d067e5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='poomsaedivision',
            unique_together={('competition', 'age_category', 'belt_group', 'style')},
        ),
        migrations.AddIndex(
            model_name='poomsaeentry',
            index=models.Index(fields=['division', 'paid'], name='competition_divisio_32b867_idx'),
        ),
        migrations.AddIndex(
            model_name='poomsaeentry',
            index=models.Index(fields=['player'], name='competition_player__294c10_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='poomsaeentry',
            unique_together={('player', 'division')},
        ),
    ]
