# Generated by Django 5.2.1 on 2025-09-29 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0034_alter_match_winner_poomsaecompetition_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnnounceResultsProxy',
        ),
        migrations.AddField(
            model_name='poomsaecompetition',
            name='competition_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ برگزاری'),
        ),
        migrations.AddField(
            model_name='poomsaecompetition',
            name='draw_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ قرعه\u200cکشی'),
        ),
    ]
