# Generated by Django 5.2.1 on 2025-09-29 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_tkdboard_ranking_total'),
        ('competitions', '0035_delete_announceresultsproxy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='poomsaecompetition',
            name='address',
            field=models.TextField(blank=True, default='', verbose_name='آدرس محل برگزاری'),
        ),
        migrations.AddField(
            model_name='poomsaecompetition',
            name='age_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='competitions.agecategory', verbose_name='گروه سنی'),
        ),
        migrations.AddField(
            model_name='poomsaecompetition',
            name='belt_groups',
            field=models.ManyToManyField(blank=True, to='competitions.beltgroup', verbose_name='گروه\u200cهای کمربندی'),
        ),
        migrations.AddField(
            model_name='poomsaecompetition',
            name='belt_level',
            field=models.CharField(blank=True, choices=[('yellow_blue', 'زرد تا آبی'), ('red_black', 'قرمز و مشکی'), ('all', 'همه رده\u200cها')], default='all', max_length=20, verbose_name='رده کمربندی'),
        ),
        migrations.AddField(
            model_name='poomsaecompetition',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='شهر محل برگزاری'),
        ),
        migrations.AddField(
            model_name='poomsaecompetition',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'آقایان'), ('female', 'بانوان')], default='', max_length=10, verbose_name='جنسیت'),
        ),
        migrations.AddField(
            model_name='poomsaecompetition',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='poomsae_posters/', verbose_name='پوستر شاخص'),
        ),
        migrations.AlterField(
            model_name='match',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='as_winner', to='accounts.userprofile', verbose_name='برنده'),
        ),
    ]
