# Generated by Django 5.2.1 on 2025-10-02 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0036_poomsaecompetition_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoachApprovalsUnifiedProxy',
            fields=[
            ],
            options={
                'verbose_name': 'تأییدهای مربیان',
                'verbose_name_plural': 'تأییدهای مربیان',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('competitions.kyorugicompetition',),
        ),
        migrations.AlterField(
            model_name='draw',
            name='age_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='draws', to='competitions.agecategory'),
        ),
        migrations.AddIndex(
            model_name='draw',
            index=models.Index(fields=['competition', 'weight_category'], name='competition_competi_21ffac_idx'),
        ),
    ]
