# Generated by Django 5.2.1 on 2025-10-02 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0037_coachapprovalsunifiedproxy_alter_draw_age_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='poomsaecompetition',
            name='age_categories',
            field=models.ManyToManyField(blank=True, related_name='poom_competitions', to='competitions.agecategory'),
        ),
    ]
