# Generated by Django 5.2.1 on 2025-10-02 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0038_poomsaecompetition_age_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='poomsaecompetition',
            name='terms_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='poomsae_competitions', to='competitions.termstemplate', verbose_name='قالب تعهدنامه'),
        ),
        migrations.CreateModel(
            name='PoomsaeFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='poomsae_files/', verbose_name='فایل PDF')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='competitions.poomsaecompetition', verbose_name='مسابقه')),
            ],
            options={
                'verbose_name': 'فایل مسابقه پومسه',
                'verbose_name_plural': 'فایل\u200cهای مسابقه پومسه',
            },
        ),
        migrations.CreateModel(
            name='PoomsaeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='poomsae_images/', verbose_name='تصویر پیوست')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='competitions.poomsaecompetition', verbose_name='مسابقه')),
            ],
            options={
                'verbose_name': 'تصویر مسابقه پومسه',
                'verbose_name_plural': 'تصاویر مسابقه پومسه',
            },
        ),
    ]
