# Generated by Django 5.2.1 on 2025-10-02 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0039_poomsaecompetition_terms_template_poomsaefile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='poomsaecompetition',
            name='registration_open',
            field=models.BooleanField(default=False, help_text='اگر تیک بخورد، ثبت\u200cنام مستقل از تاریخ\u200cهای شروع/پایان باز می\u200cماند.', verbose_name='فعال بودن ثبت\u200cنام'),
        ),
    ]
