# Generated by Django 5.2.1 on 2025-10-04 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_tkdboard_ranking_total'),
        ('competitions', '0040_poomsaecompetition_registration_open'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CoachApprovalsUnifiedProxy',
        ),
        migrations.CreateModel(
            name='CoachApprovalsEntry',
            fields=[
            ],
            options={
                'verbose_name': 'تأیید مربیان',
                'verbose_name_plural': 'تأیید مربیان',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('competitions.kyorugicompetition',),
        ),
        migrations.RemoveConstraint(
            model_name='poomsaecoachapproval',
            name='uniq_poomsae_competition_player',
        ),
        migrations.AlterField(
            model_name='poomsaecoachapproval',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='poomsae_approvals', to='accounts.userprofile', verbose_name='بازیکن'),
        ),
        migrations.AddConstraint(
            model_name='poomsaecoachapproval',
            constraint=models.UniqueConstraint(fields=('competition', 'coach'), name='uniq_poomsae_competition_coach'),
        ),
    ]
