# Generated by Django 5.2.1 on 2025-10-05 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0041_delete_coachapprovalsunifiedproxy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kyorugicompetition',
            name='slug',
            field=models.SlugField(blank=True, max_length=128, null=True, unique=True),
        ),
    ]
