# Generated by Django 5.2.1 on 2025-10-07 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0042_kyorugicompetition_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kyorugicompetition',
            name='registration_open',
        ),
        migrations.RemoveField(
            model_name='poomsaecompetition',
            name='registration_open',
        ),
        migrations.AddField(
            model_name='kyorugicompetition',
            name='registration_manual',
            field=models.BooleanField(blank=True, default=None, help_text='خالی=طبق تاریخ\u200cها، تیک=اجباراً باز، بدون تیک=اجباراً بسته', null=True, verbose_name='فعال بودن ثبت\u200cنام'),
        ),
        migrations.AddField(
            model_name='poomsaecompetition',
            name='registration_manual',
            field=models.BooleanField(blank=True, default=None, help_text='خالی=طبق تاریخ\u200cها، تیک=اجباراً باز، بدون تیک=اجباراً بسته', null=True, verbose_name='فعال بودن ثبت\u200cنام'),
        ),
    ]
