# Generated by Django 5.2.1 on 2025-10-11 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_tkdboard_ranking_total'),
        ('competitions', '0043_remove_kyorugicompetition_registration_open_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoomsaeEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coach_name', models.CharField(blank=True, default='', max_length=150, verbose_name='نام مربی (اسنپ\u200cشات)')),
                ('coach_approval_code', models.CharField(blank=True, default='', max_length=8, verbose_name='کد تایید مربی (اسنپ\u200cشات)')),
                ('club_name', models.CharField(blank=True, default='', max_length=150, verbose_name='نام باشگاه (اسنپ\u200cشات)')),
                ('board_name', models.CharField(blank=True, default='', max_length=150, verbose_name='نام هیئت (اسنپ\u200cشات)')),
                ('poomsae_type', models.CharField(choices=[('standard', 'استاندارد'), ('creative', 'ابداعی')], max_length=16, verbose_name='نوع پومسه')),
                ('insurance_number', models.CharField(max_length=20, verbose_name='شماره بیمه')),
                ('insurance_issue_date', models.DateField(verbose_name='تاریخ صدور بیمه')),
                ('status', models.CharField(choices=[('pending_payment', 'در انتظار پرداخت'), ('paid', 'پرداخت\u200cشده'), ('confirmed', 'تأیید نهایی'), ('accepted', 'پذیرفته\u200cشده'), ('completed', 'تکمیل\u200cشده'), ('canceled', 'لغو شده')], default='pending_payment', max_length=20, verbose_name='وضعیت')),
                ('is_paid', models.BooleanField(default=False, verbose_name='پرداخت شده؟')),
                ('paid_amount', models.PositiveIntegerField(default=0, verbose_name='مبلغ پرداختی (تومان)')),
                ('bank_ref_code', models.CharField(blank=True, default='', max_length=64, verbose_name='کد مرجع بانکی')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان پرداخت')),
                ('medal', models.CharField(blank=True, choices=[('', '—'), ('gold', 'طلا'), ('silver', 'نقره'), ('bronze', 'برنز')], default='', max_length=10, verbose_name='مدال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد')),
                ('age_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='poomsae_enrollments', to='competitions.agecategory', verbose_name='رده سنی')),
                ('belt_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='poomsae_enrollments', to='competitions.beltgroup', verbose_name='گروه کمربندی')),
                ('board', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='poomsae_board_enrollments', to='accounts.tkdboard', verbose_name='هیئت')),
                ('club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='poomsae_club_enrollments', to='accounts.tkdclub', verbose_name='باشگاه')),
                ('coach', models.ForeignKey(blank=True, limit_choices_to={'is_coach': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='poomsae_coach_enrollments', to='accounts.userprofile', verbose_name='مربی')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='competitions.poomsaecompetition', verbose_name='مسابقه پومسه')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='poomsae_enrollments', to='accounts.userprofile', verbose_name='بازیکن')),
            ],
            options={
                'verbose_name': 'ثبت\u200cنام پومسه',
                'verbose_name_plural': 'ثبت\u200cنام\u200cهای پومسه',
            },
        ),
        migrations.DeleteModel(
            name='PoomsaeEntry',
        ),
        migrations.AddIndex(
            model_name='poomsaeenrollment',
            index=models.Index(fields=['competition', 'status'], name='competition_competi_9529e9_idx'),
        ),
        migrations.AddIndex(
            model_name='poomsaeenrollment',
            index=models.Index(fields=['coach'], name='competition_coach_i_57664e_idx'),
        ),
        migrations.AddIndex(
            model_name='poomsaeenrollment',
            index=models.Index(fields=['club'], name='competition_club_id_cbd6c0_idx'),
        ),
        migrations.AddIndex(
            model_name='poomsaeenrollment',
            index=models.Index(fields=['board'], name='competition_board_i_552d0d_idx'),
        ),
        migrations.AddIndex(
            model_name='poomsaeenrollment',
            index=models.Index(fields=['competition', 'player'], name='competition_competi_87726b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='poomsaeenrollment',
            unique_together={('competition', 'player', 'poomsae_type')},
        ),
    ]
