# Generated by Django 5.2.1 on 2025-10-17 08:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0044_poomsaeenrollment_delete_poomsaeentry_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='kyorugicompetition',
            name='bracket_published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kyorugicompetition',
            name='bracket_published_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_kyorugi_brackets', to=settings.AUTH_USER_MODEL),
        ),
    ]
