# Generated by Django 5.2.1 on 2025-07-02 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_pendinguserprofile_coach'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendinguserprofile',
            name='coach',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_coach': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_students', to='accounts.userprofile'),
        ),
    ]
