# Generated by Django 5.2.1 on 2025-07-05 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_pendinguserprofile_coach'),
    ]

    operations = [
        migrations.AddField(
            model_name='tkdclub',
            name='founder_name',
            field=models.CharField(default=1, max_length=100, verbose_name='نام موسس'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tkdclub',
            name='founder_national_code',
            field=models.CharField(default=1, max_length=10, verbose_name='کد ملی موسس'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tkdclub',
            name='founder_phone',
            field=models.CharField(default=1, max_length=15, verbose_name='شماره موبایل موسس'),
            preserve_default=False,
        ),
    ]
