# Generated by Django 5.2.1 on 2025-07-05 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_tkdclub_founder_name_tkdclub_founder_national_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingClub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_name', models.CharField(max_length=100, unique=True, verbose_name='نام باشگاه')),
                ('founder_name', models.CharField(max_length=100)),
                ('founder_national_code', models.CharField(max_length=10)),
                ('club_type', models.CharField(choices=[('private', 'خصوصی'), ('governmental', 'دولتی'), ('other', 'سایر')], max_length=20)),
                ('activity_description', models.TextField(blank=True, null=True)),
                ('province', models.CharField(max_length=100)),
                ('county', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('tkd_board_name', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(max_length=11)),
                ('address', models.TextField()),
                ('license_number', models.CharField(max_length=100)),
                ('federation_id', models.CharField(max_length=100)),
                ('license_image', models.ImageField(upload_to='club_licenses/')),
                ('confirm_info', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('tkd_board', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_clubs', to='accounts.tkdboard')),
            ],
        ),
    ]
