# Generated by Django 5.2.1 on 2025-07-05 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_pendingclub'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingclub',
            name='founder_phone',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
