# Generated by Django 5.2.1 on 2025-07-05 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_pendingclub_founder_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pendingclub',
            options={'verbose_name': 'تاًیید باشگاه', 'verbose_name_plural': 'تاًیید باشگاه ها'},
        ),
        migrations.AlterModelOptions(
            name='tkdclub',
            options={'verbose_name': 'باشگاه', 'verbose_name_plural': 'باشگاه\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'کاربر', 'verbose_name_plural': ' کاربران'},
        ),
    ]
