# Generated by Django 5.2.1 on 2025-07-05 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_pendingclub_options_alter_tkdclub_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tkdboard',
            options={'verbose_name': 'هیئت', 'verbose_name_plural': 'هیئت\u200cها'},
        ),
    ]
