# Generated by Django 5.2.1 on 2025-07-05 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_tkdboard_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='approvedcoach',
            options={'verbose_name': 'مربی', 'verbose_name_plural': '\u200bمربی\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='approvedplayer',
            options={'verbose_name': 'بازیکن', 'verbose_name_plural': 'بازیکنان'},
        ),
        migrations.AlterModelOptions(
            name='approvedreferee',
            options={'verbose_name': 'داور', 'verbose_name_plural': '\u200b\u200bداوران'},
        ),
        migrations.AlterModelOptions(
            name='pendingclub',
            options={'verbose_name': 'تأیید باشگاه', 'verbose_name_plural': 'تأیید باشگاه\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='tkdboard',
            options={'verbose_name': 'هیئت', 'verbose_name_plural': '\u200b\u200c\u200c\u200cهیئت\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='tkdclub',
            options={'verbose_name': 'باشگاه', 'verbose_name_plural': '\u200b\u200b\u200cباشگاه\u200cها'},
        ),
    ]
