# Generated by Django 5.2.1 on 2025-07-05 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_approvedcoach_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pendingclub',
            options={'verbose_name': 'تأیید باشگاه', 'verbose_name_plural': '\u200c\u200c\u200c\u200cتأیید باشگاه\u200cها'},
        ),
    ]
