# Generated by Django 5.2.1 on 2025-07-05 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_pendingclub_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pendingplayer',
            options={'verbose_name': 'تأیید بازیکن', 'verbose_name_plural': '\u200cتأیید بازیکنان'},
        ),
        migrations.AlterModelOptions(
            name='pendingreferee',
            options={'verbose_name': 'تأیید داور', 'verbose_name_plural': '\u200c\u200c\u200cتأیید داوران'},
        ),
    ]
