# Generated by Django 5.2.1 on 2025-07-09 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_tkdclub_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingEdits',
            fields=[
            ],
            options={
                'verbose_name': 'درخواست ویرایش',
                'verbose_name_plural': 'درخواست\u200cهای ویرایش',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.pendinguserprofile',),
        ),
        migrations.AddField(
            model_name='pendinguserprofile',
            name='original_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pending_edit', to='accounts.userprofile'),
        ),
    ]
