# Generated by Django 5.2.1 on 2025-07-12 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_pendingedits_pendinguserprofile_original_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingEditProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('father_name', models.CharField(max_length=50)),
                ('birth_date', models.CharField(help_text='فرمت: ۱۴۰۳/۰۴/۱۰', max_length=10)),
                ('phone', models.CharField(max_length=11)),
                ('gender', models.CharField(choices=[('male', 'مرد'), ('female', 'زن')], max_length=10)),
                ('address', models.TextField()),
                ('province', models.CharField(max_length=50)),
                ('county', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='pending_edits/')),
                ('tkd_board_name', models.CharField(blank=True, max_length=255)),
                ('role', models.CharField(choices=[('player', 'بازیکن'), ('coach', 'مربی'), ('referee', 'داور'), ('both', 'مربی و داور')], default='player', max_length=10)),
                ('belt_grade', models.CharField(choices=[('زرد', 'زرد'), ('سبز', 'سبز'), ('آبی', 'آبی'), ('قرمز', 'قرمز'), ('مشکی دان 1', 'مشکی دان 1'), ('مشکی دان 2', 'مشکی دان 2'), ('مشکی دان 3', 'مشکی دان 3'), ('مشکی دان 4', 'مشکی دان 4'), ('مشکی دان 5', 'مشکی دان 5'), ('مشکی دان 6', 'مشکی دان 6'), ('مشکی دان 7', 'مشکی دان 7'), ('مشکی دان 8', 'مشکی دان 8'), ('مشکی دان 9', 'مشکی دان 9'), ('مشکی دان 10', 'مشکی دان 10')], max_length=20)),
                ('belt_certificate_number', models.CharField(max_length=50)),
                ('belt_certificate_date', models.CharField(max_length=10)),
                ('club_names', models.JSONField(blank=True, default=list)),
                ('coach_name', models.CharField(blank=True, max_length=255)),
                ('is_coach', models.BooleanField(default=False)),
                ('coach_level', models.CharField(blank=True, choices=[('درجه یک', 'درجه یک'), ('درجه دو', 'درجه دو'), ('درجه سه', 'درجه سه'), ('ممتاز', 'ممتاز')], max_length=20, null=True)),
                ('coach_level_International', models.CharField(blank=True, choices=[('درجه یک', 'درجه یک'), ('درجه دو', 'درجه دو'), ('درجه سه', 'درجه سه'), ('ممتاز', 'ممتاز')], max_length=20, null=True)),
                ('is_referee', models.BooleanField(default=False)),
                ('kyorogi', models.BooleanField(default=False)),
                ('poomseh', models.BooleanField(default=False)),
                ('hanmadang', models.BooleanField(default=False)),
                ('kyorogi_level', models.CharField(blank=True, choices=[('درجه یک', 'درجه یک'), ('درجه دو', 'درجه دو'), ('درجه سه', 'درجه سه'), ('ممتاز', 'ممتاز')], max_length=20, null=True)),
                ('kyorogi_level_International', models.CharField(blank=True, choices=[('درجه یک', 'درجه یک'), ('درجه دو', 'درجه دو'), ('درجه سه', 'درجه سه'), ('ممتاز', 'ممتاز')], max_length=20, null=True)),
                ('poomseh_level', models.CharField(blank=True, choices=[('درجه یک', 'درجه یک'), ('درجه دو', 'درجه دو'), ('درجه سه', 'درجه سه'), ('ممتاز', 'ممتاز')], max_length=20, null=True)),
                ('poomseh_level_International', models.CharField(blank=True, choices=[('درجه یک', 'درجه یک'), ('درجه دو', 'درجه دو'), ('درجه سه', 'درجه سه'), ('ممتاز', 'ممتاز')], max_length=20, null=True)),
                ('hanmadang_level', models.CharField(blank=True, choices=[('درجه یک', 'درجه یک'), ('درجه دو', 'درجه دو'), ('درجه سه', 'درجه سه'), ('ممتاز', 'ممتاز')], max_length=20, null=True)),
                ('hanmadang_level_International', models.CharField(blank=True, choices=[('درجه یک', 'درجه یک'), ('درجه دو', 'درجه دو'), ('درجه سه', 'درجه سه'), ('ممتاز', 'ممتاز')], max_length=20, null=True)),
                ('confirm_info', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edit_pending_members', to='accounts.tkdclub')),
                ('coach', models.ForeignKey(blank=True, limit_choices_to={'is_coach': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edit_pending_students', to='accounts.userprofile')),
                ('coaching_clubs', models.ManyToManyField(blank=True, related_name='edit_pending_coaches', to='accounts.tkdclub')),
                ('original_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='edit_request', to='accounts.userprofile')),
                ('tkd_board', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.tkdboard')),
            ],
            options={
                'verbose_name': 'درخواست ویرایش',
                'verbose_name_plural': '\u200c\u200c\u200c\u200c\u200c درخواست\u200cهای ویرایش',
            },
        ),
        migrations.DeleteModel(
            name='PendingEdits',
        ),
        migrations.RemoveField(
            model_name='pendinguserprofile',
            name='original_user',
        ),
    ]
