# Generated by Django 5.2.1 on 2025-07-12 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_pendingeditprofile_delete_pendingedits_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingeditprofile',
            name='national_code',
            field=models.CharField(default=1, max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pendingeditprofile',
            name='belt_certificate_date',
            field=models.CharField(help_text='فرمت: ۱۴۰۳/۰۴/۱۰', max_length=10),
        ),
        migrations.AlterField(
            model_name='pendingeditprofile',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_edit_members', to='accounts.tkdclub'),
        ),
        migrations.AlterField(
            model_name='pendingeditprofile',
            name='coach',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_coach': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_edit_students', to='accounts.userprofile'),
        ),
        migrations.AlterField(
            model_name='pendingeditprofile',
            name='coaching_clubs',
            field=models.ManyToManyField(blank=True, related_name='pending_edit_coaches', to='accounts.tkdclub'),
        ),
        migrations.AlterField(
            model_name='pendingeditprofile',
            name='phone',
            field=models.CharField(max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='pendingeditprofile',
            name='profile_image',
            field=models.ImageField(default=1, upload_to='pending_photos/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pendingeditprofile',
            name='tkd_board',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.tkdboard'),
        ),
    ]
