# Generated by Django 5.2.1 on 2025-07-20 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_tkdboard_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='bronze_medals',
            new_name='bronze_medals_country',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='gold_medals',
            new_name='bronze_medals_int',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='silver_medals',
            new_name='bronze_medals_ostan',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gold_medals_country',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gold_medals_int',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gold_medals_ostan',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='silver_medals_country',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='silver_medals_int',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='silver_medals_ostan',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
