# Generated by Django 5.2.1 on 2025-07-20 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_rename_bronze_medals_userprofile_bronze_medals_country_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='bronze_medals_ostan',
            new_name='bronze_medals',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='gold_medals_ostan',
            new_name='gold_medals',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='silver_medals_ostan',
            new_name='silver_medals',
        ),
    ]
