# Generated by Django 5.2.1 on 2025-07-23 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_rename_bronze_medals_ostan_userprofile_bronze_medals_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tkdclub',
            name='founder_phone',
            field=models.CharField(db_index=True, max_length=15, verbose_name='شماره موبایل موسس'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(db_index=True, max_length=11, unique=True),
        ),
    ]
