# Generated by Django 5.2.1 on 2025-07-24 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_alter_tkdclub_founder_phone_alter_userprofile_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoachClubRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('add', 'افزودن'), ('remove', 'حذف')], max_length=10)),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('accepted', 'تأیید شده'), ('rejected', 'رد شده')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.tkdclub')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_requests', to='accounts.userprofile')),
            ],
            options={
                'unique_together': {('coach', 'club', 'request_type')},
            },
        ),
    ]
