# Generated by Django 4.2.13 on 2025-09-08 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_coachclubrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='tkdboard',
            name='ranking_total',
            field=models.FloatField(default=0),
        ),
    ]
