# Generated by Django 4.2.13 on 2025-08-06 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_newsimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='headerbackground',
            options={'verbose_name': 'بک گراند هدر', 'verbose_name_plural': ' بک گراند های هدر'},
        ),
    ]
